// 名称：Shop Notify 拦截器
// 描述：拦截 shop.sxxe.net/notify 请求，直接返回 success 和 200
// 作者：Generated by AI
// 更新时间：2024-01-20

// 匹配目标URL
const targetUrl = "https://shop.sxxe.net/notify";

// 主处理函数
const handleRequest = async (request) => {
    // 直接返回 success 和 200 状态码
    const response = {
        status: 200,
        headers: {
            'Content-Type': 'text/plain; charset=utf-8',
            'Cache-Control': 'no-cache, no-store, must-revalidate'
        },
        body: 'success'
    };
    
    $done(response);
};

// 判断是否为目标请求
if ($request.url.includes(targetUrl)) {
    console.log(`[拦截通知] 拦截到请求: ${$request.url}`);
    console.log(`[拦截通知] 方法: ${$request.method}`);
    
    // 如果是GET请求，记录参数
    if ($request.method === 'GET') {
        console.log(`[拦截通知] GET参数: ${$request.url.split('?')[1] || '无参数'}`);
    }
    
    // 如果是POST请求，尝试获取请求体
    if ($request.method === 'POST' && $request.body) {
        console.log(`[拦截通知] POST参数: ${$request.body.substring(0, 200)}`);
    }
    
    handleRequest($request);
} else {
    $done({});
}
