hostname = dop.hongyibo.com.cn

# 花小猪
^https:\/\/dop\.hongyibo\.com\.cn\/kcard\/api\/package\/detail\?.*$ url script-response-body https://raw.githubusercontent.com/jeffernn/jeffern-qx/refs/heads/main/%E9%87%8D%E5%86%99/huaxiaozhu/huaxiaozhuuu.js
